---
title: "Police-Complaints"
author: "Tejas Mundhe"
date: "6/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```
```{r, include = FALSE}
raw_data <- read_csv( "https://raw.githubusercontent.com/Financial-Times/police-misconduct-complaints-analysis/main/output/philly_clean.csv" )
```
```{r, echo = FALSE}
clean_data <- raw_data %>%
  group_by(officer_id) %>%
  summarize(total = n()) %>%
  mutate(compl_decile = ntile(total, 10)) %>%
  
  group_by(compl_decile) %>%
  summarize(compl_total = sum(total)) %>%
  mutate(compl_percentage = compl_total/sum(compl_total))
```
```{r, echo = FALSE}
clean_data %>% 
  ggplot(aes(x= compl_decile, y = compl_percentage))+
  geom_col()+
  scale_x_continuous(breaks = 1:10) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  labs(title = "Police Officer Complaints by Decile",
       subtitle = "The top 10% of officers draw nearly a third of all complaints",
       x = "Officer Decile",
       y = "Percentage of Complaints",
       caption = "Financial Times (2021)")
       
  
```


